In [1]:
import pandas as pd
from urllib.parse import urlsplit
import sqlite3
import numpy as np

In [2]:
conn = sqlite3.connect("../../db/telemetry.db")

In [67]:
df = pd.read_sql_query(
    """SELECT os.event_id, os.title, os.executable, os.event_start_time, os.event_end_time,
            browser.url, browser.title AS browser_tab_title, os.previous_events
        FROM os_events
        AS os LEFT JOIN browser_events AS browser
        ON os.event_id=browser.os_event_id
        LIMIT 1000;""",
    conn,
    parse_dates = ["os_event_start_time", "os_event_end_time"]
)
df.head()

,event_id,title,executable,event_start_time,event_end_time,url,browser_tab_title,previous_events
0,e51b2531-129c-435c-ac8a-7115c3d53135,python,python.exe,2026-09-27 20:18:21,2026-09-27 20:18:23,NaN,NaN,"[{""executable"": ""Code.exe"", ""title"": ""main.py ..."
1,fbd80d54-549c-4a1a-bec6-f82b13fdfab3,python,python.exe,2026-09-27 20:18:23,2026-09-27 20:18:24,NaN,NaN,"[{""executable"": ""python.exe"", ""title"": ""python..."
2,627ac4f5-d842-417b-be55-b4f546f05e4f,python,python.exe,2026-09-27 20:18:24,2026-09-27 20:18:28,NaN,NaN,"[{""executable"": ""python.exe"", ""title"": ""python..."
3,0a21a562-3d87-48fd-ad64-11a0aaa0b46e,python,python.exe,2026-09-27 20:18:28,2026-09-27 20:21:13,NaN,NaN,"[{""executable"": ""python.exe"", ""title"": ""python..."
4,8d5134e9-5dd6-4887-9651-9f55deb68c2a,Notifications | LinkedIn - Google Chrome,chrome.exe,2026-09-27 20:21:13,2026-09-27 20:23:00,https://music.youtube.com/watch?v=QGJuMBdaqIw&...,Firework | YouTube Music,"[{""executable"": ""python.exe"", ""title"": ""python..."

In [68]:
df[df["url"].notna()]

,event_id,title,executable,event_start_time,event_end_time,url,browser_tab_title,previous_events
4,8d5134e9-5dd6-4887-9651-9f55deb68c2a,Notifications | LinkedIn - Google Chrome,chrome.exe,2026-09-27 20:21:13,2026-09-27 20:23:00,https://music.youtube.com/watch?v=QGJuMBdaqIw&...,Firework | YouTube Music,"[{""executable"": ""python.exe"", ""title"": ""python..."
5,8d5134e9-5dd6-4887-9651-9f55deb68c2a,Notifications | LinkedIn - Google Chrome,chrome.exe,2026-09-27 20:21:13,2026-09-27 20:23:00,https://music.youtube.com/watch?v=jUOdO5dqPeU&...,Firework | YouTube Music,"[{""executable"": ""python.exe"", ""title"": ""python..."
6,8d5134e9-5dd6-4887-9651-9f55deb68c2a,Notifications | LinkedIn - Google Chrome,chrome.exe,2026-09-27 20:21:13,2026-09-27 20:23:00,https://www.linkedin.com/notifications/,Notifications | LinkedIn,"[{""executable"": ""python.exe"", ""title"": ""python..."
7,8d5134e9-5dd6-4887-9651-9f55deb68c2a,Notifications | LinkedIn - Google Chrome,chrome.exe,2026-09-27 20:21:13,2026-09-27 20:23:00,https://www.linkedin.com/notifications/,Notifications | LinkedIn,"[{""executable"": ""python.exe"", ""title"": ""python..."
9,4a230187-2ee1-4ab5-ac0d-95091b3e96cf,Fix Dataclass List Default - Google Chrome,chrome.exe,2026-09-27 20:23:02,2026-09-27 20:23:20,https://chatgpt.com/c/6ab92201-19f8-83ed-814b-...,Fix Dataclass List Default,"[{""executable"": ""Code.exe"", ""title"": ""main.py ..."
...,...,...,...,...,...,...,...,...
988,3b4c95d4-854a-4bb7-9691-c9e93ec03fe7,Notifications | LinkedIn - Google Chrome,chrome.exe,2026-10-03 15:09:32,2026-10-03 15:10:16,https://www.youtube.com/watch?v=-C_rvt0SwLE&li...,Imagine Dragons - Next To Me (Audio) - YouTube,"[{""executable"": ""Telegram.exe"", ""title"": ""(2) ..."
992,4db2b560-10fe-4470-bb45-8cfcd1cae478,Netflix - Google Chrome,chrome.exe,2026-10-03 15:10:37,2026-10-03 15:10:38,https://www.netflix.com/signup?locale=uk-UA&se...,Netflix,"[{""executable"": ""explorer.exe"", ""title"": ""Task..."
996,f160ffe8-280b-4d2c-ae6a-2dc3f0cd3cee,Netflix - Google Chrome,chrome.exe,2026-10-03 15:11:45,2026-10-03 15:11:59,https://www.netflix.com/signup?locale=uk-UA&se...,Netflix,"[{""executable"": ""explorer.exe"", ""title"": ""Task..."
997,f160ffe8-280b-4d2c-ae6a-2dc3f0cd3cee,Netflix - Google Chrome,chrome.exe,2026-10-03 15:11:45,2026-10-03 15:11:59,https://www.netflix.com/signup?locale=uk-UA&se...,Netflix,"[{""executable"": ""explorer.exe"", ""title"": ""Task..."
998,f160ffe8-280b-4d2c-ae6a-2dc3f0cd3cee,Netflix - Google Chrome,chrome.exe,2026-10-03 15:11:45,2026-10-03 15:11:59,https://www.netflix.com/signup?locale=uk-UA&se...,Netflix,"[{""executable"": ""explorer.exe"", ""title"": ""Task..."

In [69]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   event_id           1000 non-null   str
 1   title              1000 non-null   str
 2   executable         1000 non-null   str
 3   event_start_time   1000 non-null   str
 4   event_end_time     1000 non-null   str
 5   url                616 non-null    str
 6   browser_tab_title  616 non-null    str
 7   previous_events    1000 non-null   str
dtypes: str(8)
memory usage: 62.6 KB

In [70]:
df.describe()

,event_id,title,executable,event_start_time,event_end_time,url,browser_tab_title,previous_events
count,1000,1000,1000,1000,1000,616,616,1000
unique,463,150,13,375,373,167,141,459
top,8d430e58-0c39-4ae9-ad2d-2b054d3f71aa,YouTube - Google Chrome,chrome.exe,2026-09-27 21:59:08,2026-09-27 22:21:11,https://www.linkedin.com/notifications/,Notifications | LinkedIn,"[{""executable"": ""Telegram.exe"", ""title"": ""\u20..."
freq,47,66,623,47,47,71,69,47

In [71]:
df['executable'].value_counts()

executable
chrome.exe                               623
Telegram.exe                             167
steamwebhelper.exe                       107
explorer.exe                              62
python.exe                                 8
Code.exe                                   6
tf_win64.exe                               6
Ride-Win64-Shipping.exe                    6
ApplicationFrameHost.exe                   5
SearchHost.exe                             4
ShellHost.exe                              3
TaleWorlds.MountAndBlade.Launcher.exe      2
StartMenuExperienceHost.exe                1
Name: count, dtype: int64

# Clean the data

In [72]:
df = df[~df['title'].isna()]
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   event_id           1000 non-null   str
 1   title              1000 non-null   str
 2   executable         1000 non-null   str
 3   event_start_time   1000 non-null   str
 4   event_end_time     1000 non-null   str
 5   url                616 non-null    str
 6   browser_tab_title  616 non-null    str
 7   previous_events    1000 non-null   str
dtypes: str(8)
memory usage: 62.6 KB

In [73]:
df[(df['executable'] != 'chrome.exe') & (~df['url'].isna())]

Empty DataFrame
Columns: [event_id, title, executable, event_start_time, event_end_time, url, browser_tab_title, previous_events]
Index: []

In [74]:
df[~df['url'].isna()]['executable'].value_counts()

executable
chrome.exe    616
Name: count, dtype: int64

In [75]:
df['url'] = np.where((df['url'].str.strip() == ''), 'chrome://newtab/', df['url'])
df['browser_tab_title'] = np.where((df['browser_tab_title'].str.strip() == ''), 'New tab', df['browser_tab_title'])
df.head()

,event_id,title,executable,event_start_time,event_end_time,url,browser_tab_title,previous_events
0,e51b2531-129c-435c-ac8a-7115c3d53135,python,python.exe,2026-09-27 20:18:21,2026-09-27 20:18:23,NaN,NaN,"[{""executable"": ""Code.exe"", ""title"": ""main.py ..."
1,fbd80d54-549c-4a1a-bec6-f82b13fdfab3,python,python.exe,2026-09-27 20:18:23,2026-09-27 20:18:24,NaN,NaN,"[{""executable"": ""python.exe"", ""title"": ""python..."
2,627ac4f5-d842-417b-be55-b4f546f05e4f,python,python.exe,2026-09-27 20:18:24,2026-09-27 20:18:28,NaN,NaN,"[{""executable"": ""python.exe"", ""title"": ""python..."
3,0a21a562-3d87-48fd-ad64-11a0aaa0b46e,python,python.exe,2026-09-27 20:18:28,2026-09-27 20:21:13,NaN,NaN,"[{""executable"": ""python.exe"", ""title"": ""python..."
4,8d5134e9-5dd6-4887-9651-9f55deb68c2a,Notifications | LinkedIn - Google Chrome,chrome.exe,2026-09-27 20:21:13,2026-09-27 20:23:00,https://music.youtube.com/watch?v=QGJuMBdaqIw&...,Firework | YouTube Music,"[{""executable"": ""python.exe"", ""title"": ""python..."

# Feature Engineering

### Constants

In [76]:
BROWSER_EXECUTABLES = [
    'chrome.exe'
]

### Utility functions

In [80]:

def get_time_information(df):
    df['week_day'] = df["event_start_time"].dt.weekday
    df['hour'] = df["event_start_time"].dt.hour
    df["duration_seconds"] = (
        df["event_end_time"] - df["event_start_time"]
    ).dt.total_seconds()

    return df

def parse_dates(df):
    df['event_start_time'] = pd.to_datetime(df['event_start_time'], format='%Y-%m-%d %H:%M:%S')
    df['event_end_time'] = pd.to_datetime(df['event_end_time'], format='%Y-%m-%d %H:%M:%S')
    return df

In [78]:
df.head()

,event_id,title,executable,event_start_time,event_end_time,url,browser_tab_title,previous_events
0,e51b2531-129c-435c-ac8a-7115c3d53135,python,python.exe,2026-09-27 20:18:21,2026-09-27 20:18:23,NaN,NaN,"[{""executable"": ""Code.exe"", ""title"": ""main.py ..."
1,fbd80d54-549c-4a1a-bec6-f82b13fdfab3,python,python.exe,2026-09-27 20:18:23,2026-09-27 20:18:24,NaN,NaN,"[{""executable"": ""python.exe"", ""title"": ""python..."
2,627ac4f5-d842-417b-be55-b4f546f05e4f,python,python.exe,2026-09-27 20:18:24,2026-09-27 20:18:28,NaN,NaN,"[{""executable"": ""python.exe"", ""title"": ""python..."
3,0a21a562-3d87-48fd-ad64-11a0aaa0b46e,python,python.exe,2026-09-27 20:18:28,2026-09-27 20:21:13,NaN,NaN,"[{""executable"": ""python.exe"", ""title"": ""python..."
4,8d5134e9-5dd6-4887-9651-9f55deb68c2a,Notifications | LinkedIn - Google Chrome,chrome.exe,2026-09-27 20:21:13,2026-09-27 20:23:00,https://music.youtube.com/watch?v=QGJuMBdaqIw&...,Firework | YouTube Music,"[{""executable"": ""python.exe"", ""title"": ""python..."

In [81]:
df = parse_dates(df)
df = get_time_information(df)
df["domain"] = df['url'].apply(lambda url: urlsplit(url).hostname if type(url)!=float else url) 
df['domain'].value_counts()

domain
www.youtube.com       308
www.linkedin.com      110
newtab                 54
www.google.com         26
jump.hito.ovh          22
www.netflix.com        20
chatgpt.com            15
music.youtube.com      11
modelistam.com.ua      11
prom.ua                10
whats-new               5
indienova.com           5
github.com              4
gamedev.dou.ua          3
www.olx.ua              3
fpvua.com               3
dou.ua                  2
steamcommunity.com      1
hotline.ua              1
www.nexusmods.com       1
www.facebook.com        1
Name: count, dtype: int64

In [82]:
df['is_os_event'] = df['executable'].isin(BROWSER_EXECUTABLES)
df = df.sort_values('is_os_event', ascending=False)
df.head()

,event_id,title,executable,event_start_time,event_end_time,url,browser_tab_title,previous_events,week_day,hour,duration_seconds,domain,is_os_event
500,26928507-783e-4042-8834-89cf02e50237,New tab - Google Chrome,chrome.exe,2026-10-03 11:49:07,2026-10-03 11:49:10,chrome://newtab/,New tab,"[{""executable"": ""steamwebhelper.exe"", ""title"":...",5,11,3.0,newtab,True
485,7e6befba-0e5c-4041-bacf-e9482083ba3c,The Entire Story Explained in 26 Minutes | GTA...,chrome.exe,2026-10-01 23:40:51,2026-10-01 23:42:50,https://www.youtube.com/shorts/S-SMfxiKcAE,Glowing 1000° Sword VS Blu🗡️🔥 - YouTube,"[{""executable"": ""Telegram.exe"", ""title"": ""\u20...",3,23,119.0,www.youtube.com,True
477,2f00594a-adf6-4a1b-85d1-160b78153a96,НОВАЧОК мене ПІДЛОВИВ та ЗІПСУВАВ катку на МІЛ...,chrome.exe,2026-10-01 23:26:51,2026-10-01 23:40:40,https://www.youtube.com/watch?v=lc_egC8i_ws,НОВАЧОК мене ПІДЛОВИВ та ЗІПСУВАВ катку на МІЛ...,"[{""executable"": ""Telegram.exe"", ""title"": ""\u20...",3,23,829.0,www.youtube.com,True
478,2f00594a-adf6-4a1b-85d1-160b78153a96,НОВАЧОК мене ПІДЛОВИВ та ЗІПСУВАВ катку на МІЛ...,chrome.exe,2026-10-01 23:26:51,2026-10-01 23:40:40,https://www.youtube.com/watch?v=lc_egC8i_ws,НОВАЧОК мене ПІДЛОВИВ та ЗІПСУВАВ катку на МІЛ...,"[{""executable"": ""Telegram.exe"", ""title"": ""\u20...",3,23,829.0,www.youtube.com,True
774,d9e8ee10-015b-4e09-8fd3-d5db20a94471,The Empire Is Finally UNITED in Bannerlord - Y...,chrome.exe,2026-10-03 13:10:17,2026-10-03 13:25:09,https://www.youtube.com/shorts/uBu3mOvfnGs,The Empire Is Finally UNITED in Bannerlord - Y...,"[{""executable"": ""steamwebhelper.exe"", ""title"":...",5,13,892.0,www.youtube.com,True

In [ ]:
import json
previous_events_df = df[['event_id', 'previous_events']]
previous_events_df['previous_events'] = previous_events_df['previous_events'].apply(json.loads)
previous_events_df = previous_events_df.explode('previous_events')
# display(previous_events_df['previous_events'].iloc[0])

# Extracting the columns from the previous events 
previous_events_df['previous_executable'] = previous_events_df['previous_events'].apply(lambda x: x.get('executable') if type(x)!=float else x)
previous_events_df['previous_publisher'] = previous_events_df['previous_events'].apply(lambda x: x.get('publisher') if type(x)!=float else x)
previous_events_df['event_start_time'] = previous_events_df['previous_events'].apply(lambda x: x.get('event_start_time') if type(x)!=float else x)
previous_events_df['event_end_time'] = previous_events_df['previous_events'].apply(lambda x: x.get('event_end_time') if type(x)!=float else x)


previous_events_df = parse_dates(previous_events_df)
previous_events_df = get_time_information(previous_events_df)

# previous_events_df['row_num'] = (
#     previous_events_df.groupby('event_id').cumcount() + 1
# )


# Aggregating the data
previous_events_df = (
    previous_events_df.groupby(
        'event_id'
    )
    .agg(
        previous_events_num_unique_executables=('previous_executable', 'nunique'),
        previous_events_num_unique_publishers=('previous_publisher', 'nunique'),
        previous_events_duration_seconds=('duration_seconds', 'sum'),
        
    )
    
)


previous_events_df.head()

,previous_events_num_unique_executables,previous_events_num_unique_publishers,previous_events_duration_seconds,row_num
event_id,,,,
000ac24d-c6f0-4486-b0e8-1efc0f070c35,1,1,302.0,1
005c8df9-3f25-4923-8aaa-4ef49981cbfa,2,2,1137.0,1
00973b46-4e6e-4063-9a83-56649df90304,2,2,304.0,1
00f774f6-eabc-4eb6-9584-896208b09796,3,3,116.0,1
0128b82e-2d24-470e-aa38-4470a34cb82d,3,3,76.0,1

In [109]:
df_flat = df
df_grouped = (
    df.groupby('event_id')
    .agg(
        title=('title', 'first'),
        executable=('executable', 'first'),
        event_start_time=('event_start_time', 'first'),
        event_end_time=('event_end_time', 'first'),
        previous_events=('previous_events', 'first'),
        week_day=('week_day', 'first'),
        hour=('hour', 'first'),
        num_unique_domains=('domain', 'nunique'),
        num_unique_urls=('url', 'nunique'),
        num_browser_events=('url','size'),
        duration_seconds=('duration_seconds', 'sum'),

    )
)
df_grouped.head()

,title,executable,event_start_time,event_end_time,previous_events,week_day,hour,num_unique_domains,num_unique_urls,num_browser_events,duration_seconds
event_id,,,,,,,,,,,
000ac24d-c6f0-4486-b0e8-1efc0f070c35,TelegramDesktop,Telegram.exe,2026-09-30 22:56:36,2026-09-30 22:56:36,"[{""executable"": ""Telegram.exe"", ""title"": ""\u20...",2,22,0,0,1,0.0
005c8df9-3f25-4923-8aaa-4ef49981cbfa,‎Юра (35438),Telegram.exe,2026-10-03 12:47:45,2026-10-03 12:48:13,"[{""executable"": ""chrome.exe"", ""title"": ""$1 Pan...",5,12,0,0,1,28.0
00973b46-4e6e-4063-9a83-56649df90304,7.5 eur to uah - Google Search - Google Chrome,chrome.exe,2026-10-03 14:28:22,2026-10-03 14:28:30,"[{""executable"": ""steamwebhelper.exe"", ""title"":...",5,14,3,3,4,32.0
00f774f6-eabc-4eb6-9584-896208b09796,Task Switching,explorer.exe,2026-09-30 22:58:56,2026-09-30 22:58:59,"[{""executable"": ""Telegram.exe"", ""title"": ""\u20...",2,22,0,0,1,3.0
0128b82e-2d24-470e-aa38-4470a34cb82d,Feed | LinkedIn - Google Chrome,chrome.exe,2026-09-27 20:33:18,2026-09-27 20:33:21,"[{""executable"": ""Code.exe"", ""title"": ""main.py ...",6,20,1,1,2,6.0

In [110]:
df_grouped = df_grouped.merge(previous_events_df, on='event_id')

In [113]:
df_grouped['previous_events_parsed'] = df_grouped['previous_events'].apply(json.loads)
properties = ['executable', 'publisher']
for i in range(5):
    for property_ in properties:
        df_grouped[f'previous_event_{i + 1}_{property_}'] = df_grouped['previous_events_parsed'].apply(lambda arr: arr[i].get(property_) if len(arr) > i else None)
df_grouped.head()

,title,executable,event_start_time,event_end_time,previous_events,week_day,hour,num_unique_domains,num_unique_urls,num_browser_events,...,previous_event_1_executable,previous_event_2_publisher,previous_event_1_publisher,previous_event_2_executable,previous_event_3_executable,previous_event_3_publisher,previous_event_4_executable,previous_event_4_publisher,previous_event_5_executable,previous_event_5_publisher
event_id,,,,,,,,,,,,,,,,,,,,,
000ac24d-c6f0-4486-b0e8-1efc0f070c35,TelegramDesktop,Telegram.exe,2026-09-30 22:56:36,2026-09-30 22:56:36,"[{""executable"": ""Telegram.exe"", ""title"": ""\u20...",2,22,0,0,1,...,Telegram.exe,Telegram FZ-LLC,Telegram FZ-LLC,Telegram.exe,Telegram.exe,Telegram FZ-LLC,Telegram.exe,Telegram FZ-LLC,Telegram.exe,Telegram FZ-LLC
005c8df9-3f25-4923-8aaa-4ef49981cbfa,‎Юра (35438),Telegram.exe,2026-10-03 12:47:45,2026-10-03 12:48:13,"[{""executable"": ""chrome.exe"", ""title"": ""$1 Pan...",5,12,0,0,1,...,chrome.exe,Telegram FZ-LLC,Google LLC,Telegram.exe,chrome.exe,Google LLC,Telegram.exe,Telegram FZ-LLC,chrome.exe,Google LLC
00973b46-4e6e-4063-9a83-56649df90304,7.5 eur to uah - Google Search - Google Chrome,chrome.exe,2026-10-03 14:28:22,2026-10-03 14:28:30,"[{""executable"": ""steamwebhelper.exe"", ""title"":...",5,14,3,3,4,...,steamwebhelper.exe,Google LLC,Valve Corporation,chrome.exe,steamwebhelper.exe,Valve Corporation,steamwebhelper.exe,Valve Corporation,steamwebhelper.exe,Valve Corporation
00f774f6-eabc-4eb6-9584-896208b09796,Task Switching,explorer.exe,2026-09-30 22:58:56,2026-09-30 22:58:59,"[{""executable"": ""Telegram.exe"", ""title"": ""\u20...",2,22,0,0,1,...,Telegram.exe,Microsoft Corporation,Telegram FZ-LLC,explorer.exe,chrome.exe,Google LLC,Telegram.exe,Telegram FZ-LLC,chrome.exe,Google LLC
0128b82e-2d24-470e-aa38-4470a34cb82d,Feed | LinkedIn - Google Chrome,chrome.exe,2026-09-27 20:33:18,2026-09-27 20:33:21,"[{""executable"": ""Code.exe"", ""title"": ""main.py ...",6,20,1,1,2,...,Code.exe,Python Software Foundation,Microsoft Corporation,python.exe,chrome.exe,Google LLC,python.exe,Python Software Foundation,chrome.exe,Google LLC

In [114]:
df_grouped.info()

<class 'pandas.DataFrame'>
Index: 463 entries, 000ac24d-c6f0-4486-b0e8-1efc0f070c35 to ff9bd399-7afd-4956-8619-6005b302e983
Data columns (total 26 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   title                                   463 non-null    str
 1   executable                              463 non-null    str
 2   event_start_time                        463 non-null    datetime64[us]
 3   event_end_time                          463 non-null    datetime64[us]
 4   previous_events                         463 non-null    str
 5   week_day                                463 non-null    int32
 6   hour                                    463 non-null    int32
 7   num_unique_domains                      463 non-null    int64
 8   num_unique_urls                         463 non-null    int64
 9   num_browser_events                      463 non-null    int64
 10  duration_seconds                        463 non-null    float64
 11  previous_events_num_unique_executables  463 non-null    int64
 12  previous_events_num_unique_publishers   463 non-null    int64
 13  previous_events_duration_seconds        463 non-null    float64
 14  row_num                                 463 non-null    int64
 15  previous_events_parsed                  463 non-null    object
 16  previous_event_1_executable             458 non-null    str
 17  previous_event_2_publisher              447 non-null    str
 18  previous_event_1_publisher              452 non-null    str
 19  previous_event_2_executable             453 non-null    str
 20  previous_event_3_executable             447 non-null    str
 21  previous_event_3_publisher              441 non-null    str
 22  previous_event_4_executable             441 non-null    str
 23  previous_event_4_publisher              435 non-null    str
 24  previous_event_5_executable             435 non-null    str
 25  previous_event_5_publisher              429 non-null    str
dtypes: datetime64[us](2), float64(2), int32(2), int64(6), object(1), str(13)
memory usage: 94.0+ KB