In [36]:
import pandas as pd
from urllib.parse import urlsplit
import sqlite3
import numpy as np

In [2]:
conn = sqlite3.connect("../../db/telemetry.db")

In [6]:
df = pd.read_sql_query(
    """SELECT os.title, os.executable, os.event_start_time AS os_event_start_time, os.event_end_time AS os_event_end_time,
            browser.url, browser.title AS browser_tab_title, browser.event_start_time AS browser_event_start_time, browser.event_end_time AS browser_event_end_time FROM os_events
        AS os LEFT JOIN browser_events AS browser
        ON os.event_id=browser.os_event_id;""",
    conn,
    parse_dates = ["os_event_start_time", "os_event_end_time", "browser_event_start_time", "browser_event_end_time"]
)
df.head()

,title,executable,os_event_start_time,os_event_end_time,url,browser_tab_title,browser_event_start_time,browser_event_end_time
0,python,python.exe,2026-09-27 20:18:21,2026-09-27 20:18:23,NaN,NaN,NaT,NaT
1,python,python.exe,2026-09-27 20:18:23,2026-09-27 20:18:24,NaN,NaN,NaT,NaT
2,python,python.exe,2026-09-27 20:18:24,2026-09-27 20:18:28,NaN,NaN,NaT,NaT
3,python,python.exe,2026-09-27 20:18:28,2026-09-27 20:21:13,NaN,NaN,NaT,NaT
4,Notifications | LinkedIn - Google Chrome,chrome.exe,2026-09-27 20:21:13,2026-09-27 20:23:00,https://music.youtube.com/watch?v=QGJuMBdaqIw&...,Firework | YouTube Music,2026-09-27 20:21:14,2026-09-27 20:21:14

In [7]:
df[df["url"].notna()]

,title,executable,os_event_start_time,os_event_end_time,url,browser_tab_title,browser_event_start_time,browser_event_end_time
4,Notifications | LinkedIn - Google Chrome,chrome.exe,2026-09-27 20:21:13,2026-09-27 20:23:00,https://music.youtube.com/watch?v=QGJuMBdaqIw&...,Firework | YouTube Music,2026-09-27 20:21:14,2026-09-27 20:21:14
5,Notifications | LinkedIn - Google Chrome,chrome.exe,2026-09-27 20:21:13,2026-09-27 20:23:00,https://music.youtube.com/watch?v=jUOdO5dqPeU&...,Firework | YouTube Music,2026-09-27 20:21:19,2026-09-27 20:21:19
6,Notifications | LinkedIn - Google Chrome,chrome.exe,2026-09-27 20:21:13,2026-09-27 20:23:00,https://www.linkedin.com/notifications/,Notifications | LinkedIn,2026-09-27 20:15:45,2026-09-27 20:15:45
7,Notifications | LinkedIn - Google Chrome,chrome.exe,2026-09-27 20:21:13,2026-09-27 20:23:00,https://www.linkedin.com/notifications/,Notifications | LinkedIn,2026-09-27 20:21:11,2026-09-27 20:21:11
9,Fix Dataclass List Default - Google Chrome,chrome.exe,2026-09-27 20:23:02,2026-09-27 20:23:20,https://chatgpt.com/c/6ab92201-19f8-83ed-814b-...,Fix Dataclass List Default,2026-09-27 20:21:51,2026-09-27 20:21:51
...,...,...,...,...,...,...,...,...
2848,"Arunesh Dillikar, PMP®, CSM® | LinkedIn - Goog...",chrome.exe,2026-10-12 22:35:56,2026-10-12 22:35:57,https://www.linkedin.com/in/aruneshd/?isSelfPr...,"Arunesh Dillikar, PMP®, CSM® | LinkedIn",2026-10-12 22:35:56,2026-10-12 22:35:56
2849,"Arunesh Dillikar, PMP®, CSM® | LinkedIn - Goog...",chrome.exe,2026-10-12 22:35:56,2026-10-12 22:35:57,https://www.linkedin.com/in/aruneshd/?isSelfPr...,Yurii Hulivatyi | LinkedIn,2026-10-12 22:35:30,2026-10-12 22:35:30
2850,"Arunesh Dillikar, PMP®, CSM® | LinkedIn - Goog...",chrome.exe,2026-10-12 22:35:56,2026-10-12 22:35:57,https://www.linkedin.com/in/aruneshd/?skipRedi...,Yurii Hulivatyi | LinkedIn,2026-10-12 22:35:30,2026-10-12 22:35:30
2851,"Arunesh Dillikar, PMP®, CSM® | LinkedIn - Goog...",chrome.exe,2026-10-12 22:35:56,2026-10-12 22:35:57,https://www.linkedin.com/in/yurii-hulivatyi/?i...,Feed | LinkedIn,2026-10-12 22:35:07,2026-10-12 22:35:07
2852,"Arunesh Dillikar, PMP®, CSM® | LinkedIn - Goog...",chrome.exe,2026-10-12 22:35:56,2026-10-12 22:35:57,https://www.linkedin.com/in/yurii-hulivatyi/?i...,Feed | LinkedIn,2026-10-12 22:35:07,2026-10-12 22:35:07

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2859 entries, 0 to 2858
Data columns (total 8 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   title                     2859 non-null   str
 1   executable                2859 non-null   str
 2   os_event_start_time       2859 non-null   datetime64[us]
 3   os_event_end_time         2859 non-null   datetime64[us]
 4   url                       1686 non-null   str
 5   browser_tab_title         1686 non-null   str
 6   browser_event_start_time  1686 non-null   datetime64[us]
 7   browser_event_end_time    1686 non-null   datetime64[us]
dtypes: datetime64[us](4), str(4)
memory usage: 178.8 KB

In [9]:
df.describe()

,os_event_start_time,os_event_end_time,browser_event_start_time,browser_event_end_time
count,2859,2859,1686,1686
mean,2026-10-05 03:47:37.700594,2026-10-05 03:51:52.138160,2026-10-05 05:05:26.518386,2026-10-05 05:05:26.518386
min,2026-09-27 20:18:21,2026-09-27 20:18:23,2026-09-27 20:15:45,2026-09-27 20:15:45
25%,2026-10-03 12:31:52,2026-10-03 12:42:50,2026-10-03 12:32:02.250000,2026-10-03 12:32:02.250000
50%,2026-10-03 19:01:38,2026-10-03 19:09:10,2026-10-03 18:47:07.500000,2026-10-03 18:47:07.500000
75%,2026-10-07 23:32:44.500000,2026-10-07 23:32:48,2026-10-07 23:30:57.500000,2026-10-07 23:30:57.500000
max,2026-10-12 22:36:08,2026-10-12 22:36:14,2026-10-12 22:35:56,2026-10-12 22:35:56

In [14]:
df['executable'].value_counts()

executable
chrome.exe                               1720
Telegram.exe                              393
explorer.exe                              283
steamwebhelper.exe                        224
Discord.exe                                40
tf_win64.exe                               29
SearchHost.exe                             19
SnippingTool.exe                           16
AlanWake2.exe                              14
PEAK.exe                                   14
Code.exe                                   10
Ride-Win64-Shipping.exe                     9
python.exe                                  8
org.telegram.messenger                      8
com.linkedin.android                        8
ShellHost.exe                               7
NVIDIA App.exe                              7
StartMenuExperienceHost.exe                 6
ApplicationFrameHost.exe                    5
com.instagram.barcelona                     4
com.instagram.android                       3
WindowsTerminal.exe                         3
Big Walk.exe                                3
Taskmgr.exe                                 3
TaleWorlds.MountAndBlade.Launcher.exe       2
LockApp.exe                                 2
msedge.exe                                  2
Acrobat.exe                                 2
steam.exe                                   2
com.google.android.gm                       2
com.glovo                                   2
com.tinder                                  1
com.openai.chatgpt                          1
com.badoo.mobile                            1
com.eway                                    1
com.google.android.apps.walletnfcrel        1
dwm.exe                                     1
com.ftband.mono                             1
com.azure.authenticator                     1
ShellExperienceHost.exe                     1
Name: count, dtype: int64

# Clean the data

In [ ]:
df['url'] = df[df['url'].isna()]

,title,executable,os_event_start_time,os_event_end_time,url,browser_tab_title,browser_event_start_time,browser_event_end_time,week_day,hour,duration_seconds,domain,is_os_event
1217,"Проектор XGIMI MoGo 4 (WK08K) [140825] – фото,...",chrome.exe,2026-10-03 15:32:50,2026-10-03 15:32:50,NaN,NaN,NaT,NaT,5,15,0.0,NaN,True
1211,"Проектор XGIMI MoGo 4 (WK08K) [140825] – фото,...",chrome.exe,2026-10-03 15:32:43,2026-10-03 15:32:43,NaN,NaN,NaT,NaT,5,15,0.0,NaN,True
1205,"Проектор XGIMI MoGo 4 (WK08K) [140825] – фото,...",chrome.exe,2026-10-03 15:32:33,2026-10-03 15:32:33,NaN,NaN,NaT,NaT,5,15,0.0,NaN,True
2367,(1) 3AM Observability Crash Course (A True Sto...,chrome.exe,2026-10-10 15:51:44,2026-10-10 15:51:52,NaN,NaN,NaT,NaT,5,15,8.0,NaN,True
1199,"Проектор XGIMI MoGo 4 (WK08K) [140825] – фото,...",chrome.exe,2026-10-03 15:32:23,2026-10-03 15:32:23,NaN,NaN,NaT,NaT,5,15,0.0,NaN,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1255,Team Fortress 2 - Direct3D 9 - 64 Bit,tf_win64.exe,2026-10-03 17:20:03,2026-10-03 17:20:04,NaN,NaN,NaT,NaT,5,17,1.0,NaN,False
1253,Task Switching,explorer.exe,2026-10-03 17:17:33,2026-10-03 17:17:33,NaN,NaN,NaT,NaT,5,17,0.0,NaN,False
1252,Team Fortress 2 - Direct3D 9 - 64 Bit,tf_win64.exe,2026-10-03 17:17:31,2026-10-03 17:17:33,NaN,NaN,NaT,NaT,5,17,2.0,NaN,False
1250,Quick Settings,ShellHost.exe,2026-10-03 17:17:01,2026-10-03 17:17:12,NaN,NaN,NaT,NaT,5,17,11.0,NaN,False
2858,Friends List,steamwebhelper.exe,2026-10-12 22:36:08,2026-10-12 22:36:14,NaN,NaN,NaT,NaT,0,22,6.0,NaN,False

In [ ]:
df = df[~df['title'].isna()]
df.info()

<class 'pandas.DataFrame'>
Index: 2859 entries, 1429 to 2858
Data columns (total 13 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   title                     2859 non-null   str
 1   executable                2859 non-null   str
 2   os_event_start_time       2859 non-null   datetime64[us]
 3   os_event_end_time         2859 non-null   datetime64[us]
 4   url                       1686 non-null   str
 5   browser_tab_title         1686 non-null   str
 6   browser_event_start_time  1686 non-null   datetime64[us]
 7   browser_event_end_time    1686 non-null   datetime64[us]
 8   week_day                  2859 non-null   int32
 9   hour                      2859 non-null   int32
 10  duration_seconds          2859 non-null   float64
 11  domain                    1543 non-null   str
 12  is_os_event               2859 non-null   bool
dtypes: bool(1), datetime64[us](4), float64(1), int32(2), str(5)
memory usage: 270.8 KB

In [15]:
df[(df['executable'] != 'chrome.exe') & (~df['url'].isna())]

Empty DataFrame
Columns: [title, executable, os_event_start_time, os_event_end_time, url, browser_tab_title, browser_event_start_time, browser_event_end_time]
Index: []

In [16]:
df[~df['url'].isna()]['executable'].value_counts()

executable
chrome.exe    1686
Name: count, dtype: int64

# Feature Engineering

### Constants

In [24]:
BROWSER_EXECUTABLES = [
    'chrome.exe'
]

In [32]:
df.iloc[1189]

title                                Notifications | LinkedIn - Google Chrome
executable                                                         chrome.exe
os_event_start_time                                       2026-09-27 20:28:39
os_event_end_time                                         2026-09-27 20:31:28
url                         https://www.linkedin.com/search/results/people...
browser_tab_title                                     Recruo: Home | LinkedIn
browser_event_start_time                                  2026-09-27 20:29:28
browser_event_end_time                                    2026-09-27 20:29:28
week_day                                                                    6
hour                                                                       20
duration_seconds                                                        169.0
domain                                                           linkedin.com
is_os_event                                                              True
Name: 40, dtype: object

In [ ]:
df['week_day'] = df["os_event_start_time"].dt.weekday
df['hour'] = df["os_event_start_time"].dt.hour
df["duration_seconds"] = (
    df["os_event_end_time"] - df["os_event_start_time"]
).dt.total_seconds()

df["domain"] = df['url'].apply(lambda url: urlsplit(url).hostname) 
df['domain'].value_counts()

AttributeError: 'float' object has no attribute 'decode'

In [25]:
df['is_os_event'] = df['executable'].isin(BROWSER_EXECUTABLES)
df = df.sort_values('is_os_event', ascending=False)
df.head()

,title,executable,os_event_start_time,os_event_end_time,url,browser_tab_title,browser_event_start_time,browser_event_end_time,week_day,hour,duration_seconds,domain,is_os_event
1429,Порівняння себе з колишнім - Google Chrome,chrome.exe,2026-10-03 19:01:38,2026-10-03 19:09:10,https://music.youtube.com/watch?v=NUVCQXMUVnI&...,YouTube Music,2026-10-03 19:01:42,2026-10-03 19:01:42,5,19,452.0,youtube.com,True
1864,Kingdom Two Crowns Tips - Playing Co op - YouT...,chrome.exe,2026-10-06 23:30:34,2026-10-06 23:37:48,https://www.linkedin.com/notifications/,Notifications | LinkedIn,2026-10-06 23:37:46,2026-10-06 23:37:46,1,23,434.0,linkedin.com,True
1191,Untitled - Google Chrome,chrome.exe,2026-10-03 15:31:58,2026-10-03 15:32:16,https://rozetka.com.ua/ua/rztk-cm-500/p529379454/,Проєктор RZTK 4K Cinema Max 500 Android HDMI –...,2026-10-03 15:31:20,2026-10-03 15:31:20,5,15,18.0,com.ua,True
1190,Untitled - Google Chrome,chrome.exe,2026-10-03 15:31:58,2026-10-03 15:32:16,https://rozetka.com.ua/ua/531560664/p531560664/,"Проектор XGIMI MoGo 4 (WK08K) [140825] – фото,...",2026-10-03 15:31:59,2026-10-03 15:31:59,5,15,18.0,com.ua,True
1189,Untitled - Google Chrome,chrome.exe,2026-10-03 15:31:58,2026-10-03 15:32:16,chrome://newtab/,New tab,2026-10-03 15:31:24,2026-10-03 15:31:24,5,15,18.0,NaN,True